ALTER TABLE BD_MONINCOMESAVING
	DROP
		CONSTRAINT FK_BD_USER_TO_BD_MONINCOMESAVING
		CASCADE;

ALTER TABLE BD_MONINCOMESAVING
	DROP
		CONSTRAINT FK_BD_MONSPEND_TO_BD_MONINCOMESAVING
		CASCADE;

ALTER TABLE BD_MONINCOMESAVING
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_BD_MONINCOMESAVING;

/* 월별수입저축상세 */
DROP TABLE BD_MONINCOMESAVING 
	CASCADE CONSTRAINTS;

/* 월별수입저축상세 */
CREATE TABLE BD_MONINCOMESAVING (
	MINCOME NUMBER(10) NOT NULL, /* 월별수입저축번호 */
	ID VARCHAR2(20), /* 아이디 */
	INCOME NUMBER(10), /* 근로소득 */
	INTEREST_INCOME NUMBER(10), /* 이자소득 */
	TINCOME NUMBER(10), /* 총수입액 */
	TSPEND NUMBER(10), /* 총지출액 */
	MSAVING NUMBER(10), /* 월저축액 */
	MSPEND NUMBER(10) /* 월별지출번호 */
);

COMMENT ON TABLE BD_MONINCOMESAVING IS '월별수입저축상세';

COMMENT ON COLUMN BD_MONINCOMESAVING.MINCOME IS '월별수입저축번호';

COMMENT ON COLUMN BD_MONINCOMESAVING.ID IS '아이디';

COMMENT ON COLUMN BD_MONINCOMESAVING.INCOME IS '근로소득';

COMMENT ON COLUMN BD_MONINCOMESAVING.INTEREST_INCOME IS '이자소득';

COMMENT ON COLUMN BD_MONINCOMESAVING.TINCOME IS '총수입액';

COMMENT ON COLUMN BD_MONINCOMESAVING.TSPEND IS '총지출액';

COMMENT ON COLUMN BD_MONINCOMESAVING.MSAVING IS '월저축액';

COMMENT ON COLUMN BD_MONINCOMESAVING.MSPEND IS '월별지출번호';

CREATE UNIQUE INDEX PK_BD_MONINCOMESAVING
	ON BD_MONINCOMESAVING (
		MINCOME ASC
	);

ALTER TABLE BD_MONINCOMESAVING
	ADD
		CONSTRAINT PK_BD_MONINCOMESAVING
		PRIMARY KEY (
			MINCOME
		);

ALTER TABLE BD_MONINCOMESAVING
	ADD
		CONSTRAINT FK_BD_USER_TO_BD_MONINCOMESAVING
		FOREIGN KEY (
			ID
		)
		REFERENCES BD_USER (
			ID
		);

ALTER TABLE BD_MONINCOMESAVING
	ADD
		CONSTRAINT FK_BD_MONSPEND_TO_BD_MONINCOMESAVING
		FOREIGN KEY (
			MSPEND
		)
		REFERENCES BD_MONSPEND (
			MSPEND
		);