ALTER TABLE BD_MONSPEND
	DROP
		CONSTRAINT FK_BD_USER_TO_BD_MONSPEND
		CASCADE;

ALTER TABLE BD_MONSPEND
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_BD_MONSPEND;

/* 월별지출상세 */
DROP TABLE BD_MONSPEND 
	CASCADE CONSTRAINTS;

/* 월별지출상세 */
CREATE TABLE BD_MONSPEND (
	id VARCHAR2(20) NOT NULL, /* 아이디 */
	MSPEND NUMBER(10) NOT NULL, /* 월별지출번호 */
	RESIDENTAL NUMBER(10), /* 주거/ 수도/광열 */
	MOBILE NUMBER(10) NOT NULL, /* 통신 */
	DAILYSUP NUMBER(10), /* 생활용품/가사서비스 */
	RESTAURENT NUMBER(10), /* 외식 */
	GROCERY NUMBER(10), /* 식료품 */
	COFFEE NUMBER(10), /* 카페 */
	ALCOHOL NUMBER(10), /* 술/담배/유흥 */
	FINANCE NUMBER(10), /* 금융/보험 */
	HEALTH NUMBER(10), /* 의료/건강 */
	CLOTHING NUMBER(10), /* 의류/신발 */
	BEAUTY NUMBER(10), /* 뷰티/미용/화장품 */
	EDUCATION NUMBER(10), /* 학습/교육 */
	CULTURE NUMBER(10), /* 문화/예술 */
	SPORTS NUMBER(10), /* 스포츠/레저 */
	TRAVEL NUMBER(10), /* 여행/숙박 */
	TRANSPORT NUMBER(10), /* 교통/차량 */
	TSPEND NUMBER(10) /* 총지출액 */
);

COMMENT ON TABLE BD_MONSPEND IS '월별지출상세';

COMMENT ON COLUMN BD_MONSPEND.id IS '아이디';

COMMENT ON COLUMN BD_MONSPEND.MSPEND IS '월별지출번호';

COMMENT ON COLUMN BD_MONSPEND.RESIDENTAL IS '주거/ 수도/광열';

COMMENT ON COLUMN BD_MONSPEND.MOBILE IS '통신';

COMMENT ON COLUMN BD_MONSPEND.DAILYSUP IS '생활용품/가사서비스';

COMMENT ON COLUMN BD_MONSPEND.RESTAURENT IS '외식';

COMMENT ON COLUMN BD_MONSPEND.GROCERY IS '식료품';

COMMENT ON COLUMN BD_MONSPEND.COFFEE IS '카페';

COMMENT ON COLUMN BD_MONSPEND.ALCOHOL IS '술/담배/유흥';

COMMENT ON COLUMN BD_MONSPEND.FINANCE IS '금융/보험';

COMMENT ON COLUMN BD_MONSPEND.HEALTH IS '의료/건강';

COMMENT ON COLUMN BD_MONSPEND.CLOTHING IS '의류/신발';

COMMENT ON COLUMN BD_MONSPEND.BEAUTY IS '뷰티/미용/화장품';

COMMENT ON COLUMN BD_MONSPEND.EDUCATION IS '학습/교육';

COMMENT ON COLUMN BD_MONSPEND.CULTURE IS '문화/예술';

COMMENT ON COLUMN BD_MONSPEND.SPORTS IS '스포츠/레저';

COMMENT ON COLUMN BD_MONSPEND.TRAVEL IS '여행/숙박';

COMMENT ON COLUMN BD_MONSPEND.TRANSPORT IS '교통/차량';

COMMENT ON COLUMN BD_MONSPEND.TSPEND IS '총지출액';

CREATE UNIQUE INDEX PK_BD_MONSPEND
	ON BD_MONSPEND (
		MSPEND ASC
	);

ALTER TABLE BD_MONSPEND
	ADD
		CONSTRAINT PK_BD_MONSPEND
		PRIMARY KEY (
			MSPEND
		);

ALTER TABLE BD_MONSPEND
	ADD
		CONSTRAINT FK_BD_USER_TO_BD_MONSPEND
		FOREIGN KEY (
			id
		)
		REFERENCES BD_USER (
			ID
		);