ALTER TABLE BD_USER
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_BD_USER;

/* 고객정보 */
DROP TABLE BD_USER 
	CASCADE CONSTRAINTS;

/* 고객정보 */
CREATE TABLE BD_USER (
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	PWD VARCHAR(20), /* 비밀번호 */
	ADDRESS VARCHAR2(50), /* 사는 지역 */
	BIRTH VARCHAR2(10), /* 생년월일 */
	INTEREST VARCHAR(50), /* 취미/관심사 */
	DEGREE VARCHAR2(20), /* 학력 */
	JOB VARCHAR2(20), /* 직업 */
	EMAIL VARCHAR2(50), /* EMAIL */
	SEX VARCHAR2(20), /* 성별 */
	ADMIN VARCHAR2(20) /* 관리자구분 */
);

COMMENT ON TABLE BD_USER IS '고객정보';

COMMENT ON COLUMN BD_USER.ID IS '아이디';

COMMENT ON COLUMN BD_USER.PWD IS '비밀번호';

COMMENT ON COLUMN BD_USER.ADDRESS IS '사는 지역';

COMMENT ON COLUMN BD_USER.BIRTH IS '생년월일';

COMMENT ON COLUMN BD_USER.INTEREST IS '취미/관심사';

COMMENT ON COLUMN BD_USER.DEGREE IS '학력';

COMMENT ON COLUMN BD_USER.JOB IS '직업';

COMMENT ON COLUMN BD_USER.EMAIL IS 'EMAIL';

COMMENT ON COLUMN BD_USER.SEX IS '성별';

COMMENT ON COLUMN BD_USER.ADMIN IS '관리자구분';

CREATE UNIQUE INDEX PK_BD_USER
	ON BD_USER (
		ID ASC
	);

ALTER TABLE BD_USER
	ADD
		CONSTRAINT PK_BD_USER
		PRIMARY KEY (
			ID
		);