-- ◀미션▶
select (MONTARGET*COUNT) from BD_GOAL where PK_GOAL=1;
select STARTDATE, FINISHDATE from BD_GOAL where PK_GOAL=1;
select MONTARGET from BD_GOAL where PK_GOAL=1;
select NOWTARGET from BD_GOAL where PK_GOAL=1;
select ACHIEVEMENT from BD_GOAL where PK_GOAL=1;

-- ◀수입▶
SELECT
  INCOME,
  INTEREST_INCOME,
  TINCOME
FROM
  BD_MONINCOMESAVING
WHERE
  MINCOME=1;

-- ◀지출▶
SELECT
  RESIDENTAL,
  MOBILE,
  TRANSPORT,
  DAILYSUP,
  RESTAURENT,
  GROCERY,
  COFFEE,
  ALCOHOL,
  FINANCE,
  HEALTH,
  CLOTHING,
  BEAUTY,
  EDUCATION,
  CULTURE,
  SPORTS,
  TRAVEL,
  TSPEND
FROM
  BD_MONSPEND
WHERE
  MSPEND=1;

-- ◀저축탭 ▶ 총소득-총지출=저축액
select TINCOME from BD_MONINCOMESAVING where MINCOME=1;
select TSPEND from BD_MONINCOMESAVING where MINCOME=1;
select (TINCOME-TSPEND) from BD_MONINCOMESAVING where MINCOME=1;